### PR TITLE
remove test for @ManagedBean

### PR DESCRIPTION
**Pull request by Ladicek**
1. The `@ManagedBean` annotation is removed in Jakarta Annotations 3.0.
2. This test was already disabled anyway.

### CODE REVIEW

**Review by geoand — APPROVED** [review]
Thanks!

**Comment by geoand** [comment]
BTW, for Quarkus to pick this up, you'll need to do an [update](https://github.com/quarkusio/quarkus/blob/2d276801a4af2a6ca48f6da616ea8f4e4ed4bfc3/tcks/resteasy-reactive/update-dependencies.sh), see [this](https://github.com/quarkusio/quarkus/blob/2d276801a4af2a6ca48f6da616ea8f4e4ed4bfc3/tcks/resteasy-reactive/README.md#resteasy-reactive-testuite-wrapper) for more details.

**Comment by Ladicek** [comment]
Thanks!

**Comment by geoand** [comment]
🙏🏼

**Pull request merged**
